// State mezclados
export const SELECCIONAR_RESTAURANTE = "SELECCIONAR_RESTAURANTE";
export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
export const SELECCIONAR_CONDUCTOR = "SELECCIONAR_CONDUCTOR";
export const SELECCIONAR_PROMO = "SELECCIONAR_PROMO";
export const SELECCIONAR_NEGOCIO = "SELECCIONAR_NEGOCIO";
export const OBTENER_CLIENTE = "OBTENER_CLIENTE";
export const OBTENER_RESTAURANTE = "OBTENER_RESTAURANTE";
